---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    extension_id: ibm.devops.services.pipeline.container.builder
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    IMAGE_NAME: my-liberty-container-v1
    USE_CACHED_LAYERS: 'true'
    COMMAND: "#!/bin/bash\n# The following colors have been defined to help with presentation\
      \ of logs: green, red, label_color, no_color.  \necho -e \"${label_color}Starting\
      \ build script${no_color}\"\n\n# set the image name\nexport IMAGE_NAME=my-liberty-container-v1\n\
      echo \"IMAGE_NAME>\"\necho $IMAGE_NAME\n\n# Build Container via Dockerfile \
      \    \n\nREGISTRY_URL=${CCS_REGISTRY_HOST}/${NAMESPACE}\nFULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:${APPLICATION_VERSION}\n\
      \n\nif [ -f Dockerfile ]; then \n    echo -e \"${label_color}Building ${FULL_REPOSITORY_NAME}\
      \ ${no_color}\"\n    BUILD_COMMAND=\"\"\n    if [ \"${USE_CACHED_LAYERS}\" ==\
      \ \"true\" ]; then \n        BUILD_COMMAND=\"ice build --pull --tag ${FULL_REPOSITORY_NAME}\
      \ ${WORKSPACE}\"\n        ${BUILD_COMMAND}\n        RESULT=$?\n    else \n \
      \       BUILD_COMMAND=\"ice build --no-cache --tag ${FULL_REPOSITORY_NAME}\
      \ ${WORKSPACE}\"\n        ${BUILD_COMMAND}\n        RESULT=$?\n    fi \n\n \
      \   if [ $RESULT -ne 0 ]; then\n        echo -e \"${red}Error building image\
      \ ${no_color}\" | tee -a \"$ERROR_LOG_FILE\"\n        echo \"Build command:\
      \ ${BUILD_COMMAND}\"\n        ice info \n        ice images\n        ${EXT_DIR}/print_help.sh\n\
      \        exit 1\n    else\n        echo -e \"${green}Container build of ${FULL_REPOSITORY_NAME}\
      \ was successful ${no_color}\"\n    fi  \nelse \n    echo -e \"${red}Dockerfile\
      \ not found in project${no_color}\"\n    exit 1\nfi  \n\n# Copy any artifacts\
      \ that will be needed for deployment and testing to $WORKSPACE    \necho \"\
      IMAGE_NAME=${FULL_REPOSITORY_NAME}\" >> $ARCHIVE_DIR/build.properties"
- name: Staging
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: ContainerDeploy
    type: deployer
    extension_id: ibm.devops.services.pipeline.docker.deploy.ice
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    PORT: 9080,22,80,443
    CONTAINER_NAME: rd-docker-liberty
    DEPLOY_TYPE: red_black
    COMMAND: |-
      #!/bin/bash
      # The following are some example deployment scripts.  Use these as is or fork them and include your updates here:
      echo -e "${label_color}Starting deployment script${no_color}"

      # get the required scripts
      git_retry clone https://www.github.com/ralfduerig/docker-scripts.git deployscripts
      /bin/bash deployscripts/deploycontainer.sh
      RESULT=$?

      # The following colors have been defined to help with presentation of logs: green, red, label_color, no_color.
      if [ $RESULT -ne 0 ]; then
          echo -e "${red}Executed failed or had warnings ${no_color}"
          ${EXT_DIR}/print_help.sh
          exit $RESULT
      fi
      echo -e "${green}Execution complete${no_label}"
